### ISSUE TITLE
ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by KnifeFed** [KBlixt/subcleaner#1]
Hey. I'm trying to run the script on Unraid but I just get:

```shell
$ python3 ./subcleaner.py
Traceback (most recent call last):
  File "/mnt/user/scripts/subcleaner/./subcleaner.py", line 3, in <module>
    from subcleaner.main import main
  File "/mnt/user/scripts/subcleaner/subcleaner/main.py", line 6, in <module>
    from .cleaner import Cleaner
  File "/mnt/user/scripts/subcleaner/subcleaner/cleaner.py", line 1, in <module>
    from .subtitle import Subtitle
  File "/mnt/user/scripts/subcleaner/subcleaner/subtitle.py", line 2, in <module>
    from libs.langdetect import detect_langs
  File "/mnt/user/scripts/subcleaner/libs/langdetect/__init__.py", line 1, in <module>
    from .detector_factory import DetectorFactory, PROFILES_DIRECTORY, detect, detect_langs
  File "/mnt/user/scripts/subcleaner/libs/langdetect/detector_factory.py", line 10, in <module>
    from .detector import Detector
  File "/mnt/user/scripts/subcleaner/libs/langdetect/detector.py", line 4, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

Is there some dependency I'm missing?

**Comment by KBlixt** [comment]
mh, try installing the six module. this module usually comes pre-installed with python but maybe not in unraid?
will investigate and might change some code but for you it's a fairly straight forward fix, just install the six module.

**Comment by KnifeFed** [comment]
Well, that was easy. Thank you :)
